### ISSUE TITLE
wchar_t versus wchar, deprecation warnings

### ISSUE THREAD

**Issue by DannyArends** [ariovistus/pyd#111]
Two minor issues I ran into:

1) I ran into a memory corruption issue when setting Py_SetPath before calling py_init(), I tracked it down to wchar being used where python uses wchar_t. Using wchar_t from core.stdc.stddef fixed the issue

2) The new dmd version (2.086.0) complains about the class allocators in multi_index.d, see: https://dlang.org/deprecate.html#Class%20allocators%20and%20deallocators

I fixed both issues in the master branch of my own fork: https://github.com/DannyArends/pyd

How to merge these changes into pyd? should I just submit a pull request ? if so, to which branch ?

**Comment by ariovistus** [comment]
I have a separate repo for multi_index here: https://github.com/ariovistus/multi_index, which I keep in sync with pyd in a not great way. but it has a test suite that probably exercises multi_index better than pyd's, so could you make a PR there first? I have a feeling your changes have some implications that will need to be explored a bit.
Otherwise, ya, PR master branch is fine

**Comment by DannyArends** [comment]
First off sorry for the late response, I have been traveling recently.
I'll split up the commits into 2 and submit the multi_index stuff to the multi_index repository. Is the code between this repository and the pyd repository kept synchronized in some way ?

**Comment by ariovistus** [comment]
no, its manual, so you might as well leave your changes alone in this this repo
