### ISSUE TITLE
pyd vs cython 

### ISSUE THREAD

**Issue by liveresume** [ariovistus/pyd#66]
I am wondering what the difference would be between:
- Using pyd to embed Python code in a D project, vs. 
- Compiling a Python project to a shared object with Cython, then using D's C FFI to call the Cython code.

The way I see it:
- There should be a significant speedup (has to do with Python not D)
- Any of the 3 D compilers should work.

Just picking up with Python+D weighing my options and looking for clarification.

**Comment by ariovistus** [comment]
Haven't really used cython, but all else being equal, I would tend to expect code produced by it to be faster than embedding python in d, if only because you aren't running the python through an interpreter. At the end of the day, both are going to be hitting the python C API. cython is probably more efficient at that.

I think the biggest difference between your two strategies would be integration of the results with your d code. With cython, it would be on you to write the headers for your shared objects and deal with data conversion and exceptions across that boundary. pyd does that stuff for you, but that might not matter if the interface between your python code and d code is small. also, it might be easier to shift speed critical sections of code from python to d with pyd than cython.

**Comment by BryanARivera** [comment]
@ariovistus Thanks for the info.  Cython actually produces header files so it should be a breeze to embed.  Also the data conversion should be unnecessary since Cython uses C types rather than Python types.

**Comment by liveresume** [comment]
@ariovistus Would appreciate your input after you've had time to checkout cython.

Maybe it's within reason to note on readme that pyd is more for D in Python rather than vice-versa?

**Comment by ariovistus** [comment]
No, pyd works fine with python in d. better than the reverse, actually, if your measure is the number of D compilers that can even produce shared libraries.

**Comment by liveresume** [comment]
@ariovistus I see your point.  The big difference for me is that Cython is much faster than Python.
